apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: pythontodo
        image: sushma7/todo-list-app:latest
        ports:
        - containerPort: 8000
